##
## ETNA PROJECT, 05/11/2021 by Anthony LECLERCQ
## [...]
## File description:
##      [...]
##


MyCrd:
	gcc -c ../c/main.c ../c/my_readline_test.c ../c/my_strcmp.c ../c/my_strcat.c -Wall -W -I./../h/

	gcc -o ../Release/my_crd *.o



clean:
		rm -f ../c/*.o ../h/*.o ../c/*.~ ../h/*.~ ./*.~ ./*.o

